// This file is auto-generated by scripts/generate_vfs.js. Do not modify manually.
export const virtualFS = {
  "archive": {},
  "assets": {
    "favicon": {
      "favicon.ico": "file"
    },
    "fonts": {
      "FiraCode-VF.woff2": "file"
    },
    "images": {
      "buddies": {
        "chenghao.li.png": "file",
        "decal.ocf.berkeley.edu.png": "file",
        "jaysa.net.png": "file",
        "joewang.me.png": "file",
        "ocf.berkeley.edu.png": "file",
        "sawansri.com.png": "file"
      }
    },
    "overlays": {
      "crt.webp": "file"
    }
  },
  "css": {
    "base.css": "file",
    "components.css": "file",
    "editors.css": "file",
    "terminal.css": "file"
  },
  "index.html": "file",
  "info": {
    "about.md": "file",
    "contact.md": "file",
    "projects.md": "file"
  },
  "js": {
    "audio.js": "file",
    "buddies.js": "file",
    "commands": {
      "audio": {
        "mute.js": "file",
        "sound.js": "file",
        "unmute.js": "file"
      },
      "filesystem": {
        "cat.js": "file",
        "cd.js": "file",
        "ls.js": "file",
        "mkdir.js": "file",
        "nano.js": "file",
        "rm.js": "file",
        "touch.js": "file",
        "vim.js": "file"
      },
      "games": {
        "invaders.js": "file",
        "minesweeper.js": "file",
        "pong.js": "file",
        "snake.js": "file",
        "sokoban.js": "file",
        "tetris.js": "file"
      },
      "general": {
        "buddies.js": "file",
        "clear.js": "file",
        "date.js": "file",
        "echo.js": "file",
        "help.js": "file",
        "llm.js": "file",
        "neofetch.js": "file",
        "ping.js": "file",
        "sudo.js": "file",
        "whoami.js": "file"
      },
      "index.js": "file"
    },
    "fs.js": "file",
    "fs_manifest.js": "file",
    "main.js": "file",
    "shell.js": "file",
    "utils": {
      "editor.js": "file",
      "markdown.js": "file"
    }
  },
  "README.md": "file",
  "sokoban": {
    "level1.txt": "file",
    "level2.txt": "file",
    "level3.txt": "file",
    "README.md": "file"
  }
};
