const fs = require('fs');
const crypto = require('crypto');
const pathModule = require('path');
const { pathToFileURL } = require('url');

// Mock browser globals for Node.js import evaluation
global.localStorage = {
  getItem: () => null,
  setItem: () => null
};
global.document = {
  addEventListener: () => null,
  removeEventListener: () => null
};
global.window = {
  AudioContext: class {},
  webkitAudioContext: class {}
};

const IGNORED_NAMES = new Set([
  '.git',
  '.github',
  'CNAME',
  'scripts',
  'node_modules'
]);

const IGNORED_PATHS = new Set([
  'archive/index.html',
  '.gitignore',
  'js/fs_manifest.js',
  'js/commands/index.js'
]);

// Core files that form a dependency cycle with fs_manifest.js
const CYCLIC_PATHS = new Set([
  'index.html',
  'js/main.js',
  'js/fs.js',
  'js/shell.js',
  'js/commands/index.js',
  'js/utils/markdown.js',
  'js/audio.js',
  'js/buddies.js'
]);

// Recursively find files
function getFiles(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const name = pathModule.join(dir, file);
    if (fs.statSync(name).isDirectory()) {
      if (file !== '.git' && file !== 'node_modules' && file !== 'scripts') {
        getFiles(name, fileList);
      }
    } else {
      if (file.endsWith('.js') || file.endsWith('.html') || file.endsWith('.css')) {
        fileList.push(pathModule.relative('.', name).replace(/\\/g, '/'));
      }
    }
  }
  return fileList;
}

function getHash(content) {
  return crypto.createHash('sha256').update(content).digest('hex').slice(0, 10);
}

function resolveImportPath(sourceFile, importPath) {
  const cleanImportPath = importPath.split('?')[0];
  const dir = pathModule.dirname(sourceFile);
  const resolved = pathModule.resolve(dir, cleanImportPath);
  return pathModule.relative('.', resolved).replace(/\\/g, '/');
}

function buildVfsTree(dir, fileHashes = {}) {
  const tree = {};
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const name = entry.name;
    if (IGNORED_NAMES.has(name)) {
      continue;
    }

    const fullPath = pathModule.join(dir, name);
    const relPath = pathModule.relative('.', fullPath).replace(/\\/g, '/');
    if (IGNORED_PATHS.has(relPath)) {
      continue;
    }

    if (entry.isDirectory()) {
      tree[name] = buildVfsTree(fullPath, fileHashes);
    } else if (entry.isFile()) {
      if (CYCLIC_PATHS.has(relPath)) {
        tree[name] = "core";
      } else if (fileHashes[relPath] !== undefined) {
        tree[name] = fileHashes[relPath];
      } else {
        const content = fs.readFileSync(fullPath);
        tree[name] = getHash(content);
      }
    }
  }
  return tree;
}

function generateManifestContent(vfsTree) {
  return `// This file is auto-generated by scripts/generate_vfs.js. Do not modify manually.
export const virtualFS = ${JSON.stringify(vfsTree, null, 2)};
`;
}

async function generateCommandsIndexContent() {
  const commandsDir = pathModule.join(__dirname, '..', 'js', 'commands');
  const categories = ['general', 'filesystem', 'audio', 'games'];
  const imports = [];
  const eagerCommands = [];
  const lazyCommands = [];

  for (const category of categories) {
    const categoryDir = pathModule.join(commandsDir, category);
    if (!fs.existsSync(categoryDir)) continue;

    const files = fs.readdirSync(categoryDir);
    for (const file of files) {
      if (!file.endsWith('.js')) continue;

      const cmdName = file.slice(0, -3);
      const filePath = pathModule.join(categoryDir, file);
      const fileUrl = pathToFileURL(filePath).href;

      try {
        const module = await import(fileUrl);
        const cmd = module[cmdName];
        if (!cmd) {
          console.warn(`Command export not found for ${cmdName} in ${filePath}`);
          continue;
        }

        const cleanCategory = category === 'games' ? 'game' : category;

        if (cmd.lazy) {
          lazyCommands.push({
            name: cmdName,
            description: cmd.description || '',
            category: cleanCategory,
            args: cmd.args || [],
            importPath: `./${category}/${file}`
          });
        } else {
          imports.push(`import { ${cmdName} } from './${category}/${file}';`);
          eagerCommands.push(cmdName);
        }
      } catch (err) {
        console.error(`Failed to import command file ${filePath}:`, err);
      }
    }
  }

  // Format imports section
  let content = `// Eagerly loaded core and helper commands
${imports.join('\n')}

export const commands = {
  // Eagerly loaded
${eagerCommands.map(name => `  ${name},`).join('\n')}

  // Lazy loaded commands (loaded on-demand and preloaded in background on boot)
`;

  // Format lazy commands
  const formattedLazy = lazyCommands.map(cmd => {
    return `  ${cmd.name}: {
    name: '${cmd.name}',
    description: ${JSON.stringify(cmd.description)},
    category: '${cmd.category}',
    args: ${JSON.stringify(cmd.args, null, 4).replace(/\n/g, '\n    ')},
    lazy: true,
    import: () => import('${cmd.importPath}')
  }`;
  }).join(',\n');

  content += formattedLazy + '\n};\n';
  return content;
}

async function runCacheBuster() {
  const files = getFiles('.');
  if (!files.includes('js/fs_manifest.js')) {
    files.push('js/fs_manifest.js');
  }
  if (!files.includes('js/commands/index.js')) {
    files.push('js/commands/index.js');
  }

  // Initialize file hashes with raw contents
  const fileHashes = {};
  const fileContents = {};

  for (const file of files) {
    let content = '';
    if (fs.existsSync(file)) {
      content = fs.readFileSync(file, 'utf8');
    }
    fileContents[file] = content;
    fileHashes[file] = getHash(content);
  }

  // Iterative hash propagation
  let iterations = 0;
  const MAX_ITERATIONS = 10;
  let stable = false;

  while (!stable && iterations < MAX_ITERATIONS) {
    stable = true;
    iterations++;

    // 1. Regenerate commands/index.js in-memory
    const newIndexContent = await generateCommandsIndexContent();
    if (fileContents['js/commands/index.js'] !== newIndexContent) {
      fileContents['js/commands/index.js'] = newIndexContent;
      const newHash = getHash(newIndexContent);
      if (fileHashes['js/commands/index.js'] !== newHash) {
        fileHashes['js/commands/index.js'] = newHash;
        stable = false; // Trigger another pass to propagate this updated index hash
      }
    }

    // 2. Regenerate VFS manifest in-memory using the current fileHashes
    const vfsTree = buildVfsTree('.', fileHashes);
    const newManifestContent = generateManifestContent(vfsTree);

    if (fileContents['js/fs_manifest.js'] !== newManifestContent) {
      fileContents['js/fs_manifest.js'] = newManifestContent;
      const newHash = getHash(newManifestContent);
      if (fileHashes['js/fs_manifest.js'] !== newHash) {
        fileHashes['js/fs_manifest.js'] = newHash;
        stable = false; // Trigger another pass to propagate this updated manifest hash
      }
    }

    // 3. Standard CSS and JS hash propagation
    for (const file of files) {
      if (file === 'js/fs_manifest.js' || file === 'js/commands/index.js') continue;

      let content = fileContents[file];
      let originalContent = content;

      if (file.endsWith('.html')) {
        // Replace CSS references
        content = content.replace(/(href=["'])(css\/.*?\.css)(?:\?v=[^"']*)?(["'])/g, (match, p1, p2, p3) => {
          const targetPath = resolveImportPath(file, p2);
          const hash = fileHashes[targetPath] || '';
          return `${p1}${p2}?v=${hash}${p3}`;
        });
        // Replace JS references
        content = content.replace(/(src=["'])(js\/.*?\.js)(?:\?v=[^"']*)?(["'])/g, (match, p1, p2, p3) => {
          const targetPath = resolveImportPath(file, p2);
          const hash = fileHashes[targetPath] || '';
          return `${p1}${p2}?v=${hash}${p3}`;
        });
      } else if (file.endsWith('.js')) {
        // Replace static imports
        content = content.replace(/(from\s+['"])((?:\.|\/|\.\.)\/.*?\.js)(?:\?v=[^'"]*)?(['"])/g, (match, p1, p2, p3) => {
          const targetPath = resolveImportPath(file, p2);
          const hash = fileHashes[targetPath] || '';
          return `${p1}${p2}?v=${hash}${p3}`;
        });
        // Replace dynamic imports
        content = content.replace(/(import\(['"])((?:\.|\/|\.\.)\/.*?\.js)(?:\?v=[^'"]*)?(['"]\))/g, (match, p1, p2, p3) => {
          const targetPath = resolveImportPath(file, p2);
          const hash = fileHashes[targetPath] || '';
          return `${p1}${p2}?v=${hash}${p3}`;
        });
      }

      if (content !== originalContent) {
        fileContents[file] = content;
        const newHash = getHash(content);
        if (newHash !== fileHashes[file]) {
          fileHashes[file] = newHash;
          stable = false; // Trigger another pass to propagate this file's updated hash to its importers
        }
      }
    }
  }

  const isCI = process.env.CI || process.env.GITHUB_ACTIONS || process.argv.includes('--write');

  if (isCI) {
    // Write the fully updated contents to disk
    for (const file of files) {
      const dir = pathModule.dirname(file);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      fs.writeFileSync(file, fileContents[file], 'utf8');
    }
    console.log(`Cache busted, VFS manifest, and command index generated successfully in ${iterations} passes.`);
  } else {
    console.log(`[Dry Run] Cache buster, VFS manifest, and command index calculated content hashes in ${iterations} passes.`);
    console.log(`Local run detected: files were NOT modified on disk.`);
    console.log(`To write these changes to your local files, run: node scripts/cache_buster.js --write`);
  }
}

module.exports = {
  getHash,
  buildVfsTree,
  generateManifestContent,
  generateCommandsIndexContent,
  runCacheBuster
};

if (require.main === module) {
  runCacheBuster().catch(console.error);
}
