const fs = require('fs');
const path = require('path');

const IGNORED_NAMES = new Set([
  '.git',
  '.github',
  'CNAME',
  'scripts',
  'node_modules'
]);

const IGNORED_PATHS = new Set([
  'archive/index.html'
]);

function buildVfsTree(dir) {
  const tree = {};
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const name = entry.name;
    if (IGNORED_NAMES.has(name)) {
      continue;
    }

    const fullPath = path.join(dir, name);
    const relPath = path.relative('.', fullPath).replace(/\\/g, '/');
    if (IGNORED_PATHS.has(relPath)) {
      continue;
    }

    if (entry.isDirectory()) {
      tree[name] = buildVfsTree(fullPath);
    } else if (entry.isFile()) {
      tree[name] = "file";
    }
  }
  return tree;
}

const vfsTree = buildVfsTree('.');
const outputContent = `// This file is auto-generated by scripts/generate_vfs.js. Do not modify manually.
export const virtualFS = ${JSON.stringify(vfsTree, null, 2)};
`;

fs.writeFileSync(path.join('js', 'fs_manifest.js'), outputContent, 'utf8');
console.log('Virtual File System manifest generated successfully in js/fs_manifest.js');
